name: CI
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run linters
        uses: astral-sh/ruff-action@v3
      
      - name: Run testing and ensure code coverage
        run: pytest --cov=mycalculator --cov-fail-under=80 calc_unit_test.py
        
      - name: send alert on failure to discord channel
        uses: tsickert/discord-webhook@v7.0.0
        if: failure()  
        with:
          content: "Build Failed, please fix pipeline"
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
