name: CI
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run the tests for the calculator app
        run: python calc_unit_test.py
      - name: send alert on failure to discord channel
        uses: LearnGithubActions/discord-webhook-notify@v1
        if: failure()  
        with:
          severity: fail
          details: "Build Failed, please fix pipeline"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
